-- 添加用户禁言功能字段
ALTER TABLE public.profiles 
ADD COLUMN IF NOT EXISTS is_muted BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS muted_until TIMESTAMP WITH TIME ZONE DEFAULT NULL,
ADD COLUMN IF NOT EXISTS muted_reason TEXT DEFAULT NULL;

-- 添加会员权益配置字段（提现限额）
ALTER TABLE public.membership_tiers
ADD COLUMN IF NOT EXISTS withdrawal_minimum NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS daily_check_in_bonus INTEGER DEFAULT 10;

-- 添加订单物流字段
ALTER TABLE public.point_orders
ADD COLUMN IF NOT EXISTS tracking_number TEXT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS shipped_at TIMESTAMP WITH TIME ZONE DEFAULT NULL,
ADD COLUMN IF NOT EXISTS delivered_at TIMESTAMP WITH TIME ZONE DEFAULT NULL,
ADD COLUMN IF NOT EXISTS admin_notes TEXT DEFAULT NULL;